export const gyms: { [key: number]: string } = {
	0: "Cortondo - Bug Gym (bug, level 14-15)",
	8: "South Province (Area Three) - Stony Cliff Titan (rock, level 16)",
	1: "Artazon - Grass Gym (grass, level 16-18)",
	9: "West Province (Area One) - Open Sky Titan (flying, level 19)",
	2: "Levincia - Electric Gym (electric, level 23-24)",
	13: "West Province (Area One) - Team Star Dark Crew (level 20-21)",
	10: "East Province (Area Three) - Lurking Steel Titan (steel, level 28)",
	14: "East Province (Area One) - Team Star Fire Crew (level 26-27)",
	3: "Cascarrafa - Water Gym (water, level 29-30)",
	15: "Tagtree Thicket - Team Star Poison Crew (level 32-33)",
	4: "Medali - Normal Gym (normal, level 35-36)",
	5: "Montenevera - Ghost Gym (ghost, level 41-42)",
	11: "Asado Desert - Quaking Earth Titan (ground, level 44)",
	6: "Alfornada - Psychic Gym (psychic, level 44-45)",
	7: "Glaseado - Ice Gym (ice, level 47-48)",
	16: "North Province (Area Three) - Team Star Fairy Crew (level 50-51)",
	12: "Casseroya Lake - False Dragon Titan (dragon, level 55)",
	17: "North Province (Area One) - Team Star Fighting Crew (level 55-56)",
	18: "Elite Four",
	19: "Paldea Champion",
	20: "Director Clavell - Uva/Naranja Academy",
	21: "Arven - Poco Path Lighthouse",
	22: "Cassiopeia - Uva/Naranja Academy",
	23: "Nemona - Uva/Naranja Academy",
	24: "Professor Sada/Turo - Area Zero",
	25: "Post-Game Gym Rematches",
	26: "Ace Academy Tournament",
};
